package ru.finex.core.cluster;

import org.redisson.api.RObject;
import org.redisson.api.RedissonClient;

import javax.annotation.PreDestroy;

/**
 * @author m0nster.mind
 */
public interface ClusterService {

    /**
     * Redisson client.
     * @return {@link RedissonClient}
     */
    RedissonClient getClient();

    /**
     * Return server role.
     * @return role
     */
    String getRole();

    /**
     * Return name of object with role.
     * @param name name of object
     * @return name of object with role
     */
    String getName(String name);

    /**
     * Return name of object with role generated by the caller canonical name.
     * @param caller the caller
     * @return name of object
     */
    String getName(Class<?> caller);

    /**
     * Return name of object with role and the field, generated by the caller canonical name.
     * @param caller the caller
     * @param field the field
     * @return name of object
     */
    String getName(Class<?> caller, String field);

    String getName(Class<?> caller, String method, String parameter);

    /**
     * Return count of this server instances (by role) in cluster.
     * @return server instances
     */
    int getInstances();

    /**
     * Register clustered resource as managed.
     * All resources registered as managed will be deleted at {@link PreDestroy PreDestroy} signal
     *  if current server instance with specified role is single.
     * @param resource clustered resource
     */
    void registerManagedResource(RObject resource);

}
