package ru.finex.core.cluster;

import org.redisson.api.RedissonClient;

/**
 * @author m0nster.mind
 */
public interface ClusterService {

    /**
     * Redisson client.
     * @return {@link RedissonClient}
     */
    RedissonClient getClient();

    /**
     * Return server role.
     * @return role
     */
    String getRole();

    /**
     * Return name of object with role.
     * @param name name of object
     * @return name of object with role
     */
    String getName(String name);

    /**
     * Return name of object with role generated by the caller canonical name.
     * @param caller the caller
     * @return name of object
     */
    String getName(Class<?> caller);

    /**
     * Return name of object with role and the field, generated by the caller canonical name.
     * @param caller the caller
     * @param field the field
     * @return name of object
     */
    String getName(Class<?> caller, String field);

    /**
     * Return count of this server instances (by role) in cluster.
     * @return server instances
     */
    int getInstances();

}
